version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sgt_mysql
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede
    ports:
      - "3306:3306"

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: sgt_laravel
    volumes:
      - ./laravel:/var/www/html
    networks:
      - minha_rede
    ports:
      - "8000:80"
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  minha_rede:
